# permissions for end users to edit entandoappv2s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: entandoupgrade-editor-role
rules:
- apiGroups:
  - app.entando.org
  resources:
  - entandoappv2s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.entando.org
  resources:
  - entandoappv2s/status
  verbs:
  - get
