# permissions for end users to view entandoappv2s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: entandoupgrade-viewer-role
rules:
- apiGroups:
  - app.entando.org
  resources:
  - entandoappv2s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.entando.org
  resources:
  - entandoappv2s/status
  verbs:
  - get
