---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - upgrade.entando.org
  resources:
  - entandoupgrades
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - upgrade.entando.org
  resources:
  - entandoupgrades/finalizers
  verbs:
  - update
- apiGroups:
  - upgrade.entando.org
  resources:
  - entandoupgrades/status
  verbs:
  - get
  - patch
  - update
