---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.entando.org
  resources:
  - entandoappv2s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.entando.org
  resources:
  - entandoappv2s/finalizers
  verbs:
  - update
- apiGroups:
  - app.entando.org
  resources:
  - entandoappv2s/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operators.coreos.com
  resources:
  - clusterserviceversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
