apiVersion: app.entando.org/v1alpha1
kind: EntandoAppV2
metadata:
  name: entando-app-v2-sample
spec:
  version: 7.1.0
  entandoAppName: my-app
  commonEnvironmentVariables:
    - name: CUSTOM_ENV
      value: test
    - name: TO_OVERRIDE_1
      value: SUCCESS
  appBuilder:
    environmentVariables:
      - name: CUSTOM_ENV
        value: test
    imageOverride: "test/test:12"
  componentManager:
    environmentVariables:
      - name: CUSTOM_ENV_CM
        value: test
      - name: TO_OVERRIDE_1
        value: SUCCESS_1_CM
    # 7.1.0
    # imageOverride: "entando/entando-component-manager:7.1.0"
    # 7.1.1
    imageOverride: "entando/entando-component-manager:7.1.1"
  keycloak:
    environmentVariables:
      - name: CUSTOM_ENV_KC
        value: test_ks
      - name: TO_OVERRIDE_1
        value: SUCCESS_1_KC
    externalService: false
